[workspace]
members = ["hydra", "hydra-test"]
resolver = "2"


[workspace.dependencies]
flume = "0.11"
once_cell = "1.19"
bitflags = "2.4"
pin-project-lite = "0.2"
serde = { version = "1.0", default-features = false, features = ["derive"] }
tokio = { version = "1.0", default-features = false, features = ["rt", "rt-multi-thread", "net", "sync", "time", "macros"] }
