[package]
name = "hydra"
version = "0.1.0"
edition = "2021"

[features]
default = ["json", "macros"]
json = ["dep:serde_json"]
macros = ["dep:hydra-macros"]

[dependencies]
flume.workspace = true
bytes.workspace = true
sha2.workspace = true
hmac.workspace = true
dashmap.workspace = true
tokio.workspace = true
tokio-util.workspace = true
futures-util.workspace = true
bincode.workspace = true
serde.workspace = true
once_cell.workspace = true
bitflags.workspace = true
pin-project-lite.workspace = true

hydra-macros = { workspace = true, optional = true }

serde_json = { workspace = true, optional = true }
