[package]
name = "hydra-macros"
version = "0.1.1"
edition = "2021"
license-file.workspace = true
description = "Macros for the Hydra framework."

[lib]
proc-macro = true

[dependencies]
quote = "1"
syn = { version = "2.0", features = ["full"] }
