[package]
name = "hydra-test-client"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
hydra = { path = "../hydra", default-features = false, features = ["tracing", "macros"] }

serde.workspace = true
