[package]
name = "hydra-test"
version = "0.1.0"
edition = "2021"

[dependencies]
hydra = { path = "../hydra", features = ["json", "tracing"] }
tracing = "0.1"
tracing-subscriber = "0.3"

tokio.workspace = true
serde.workspace = true
