[package]
name = "hydra-test"
version = "0.1.0"
edition = "2021"

[dependencies]
hydra = { path = "../hydra", features = ["json"] }
hydra-platform = { path = "../hydra-platform" }

tokio.workspace = true
serde.workspace = true
