[package]
name = "hydra-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hydra = { path = "../hydra" }
hydra-platform = { path = "../hydra-platform" }

tokio.workspace = true
